XmacsLabs/lolly

- System/Classes/tm_timer.cpp
- System/Classes/tm_timer.hpp
- System/config_l1.h.xmake
- tests/System/Classes/tm_timer_test.cpp
While conducting unit tests, I noticed that in the tm_timer functions, the tm_ostream parameter was not being passed by reference. This caused the memory of tm_ostream to be deallocated when the function finished, resulting in unexpected null pointers. Therefore, I changed these parameters to be passed by reference.
> fix tm_timer

- Kernel/Types/generic_tree.hpp
- tests/Kernel/Types/generic_tree_test.cpp
I think Joris did not complete generic_tree.hpp. The provided interface is too limited.
And no file uses this structure.
> [2_3] add generic_tree_test

- tests/Kernel/Types/modification_test.cpp
> [2_3] add modification_test

- xmake.lua
To avoid including both mimalloc and jemalloc
> [8_1] merge option in xmake

- xmake.lua
Because we are using `add_forceincludes`.
https://xmake.io/#/manual/project_target?id=targetadd_forceincludes
> [11_4] set minimal xmake version to 2.8.2

- Kernel/Types/analyze.cpp
- Kernel/Types/analyze.hpp
- tests/Kernel/Types/analyze_test.cpp
- xmake.lua
To add Chinese numeral in mogan.
> [17_1] Add hanzi_nr to convert numbers to Chinese numerals

- System/IO/tm_ostream.cpp
- System/IO/tm_ostream.hpp
- tests/System/Classes/tm_timer_test.cpp
- tests/System/IO/tm_ostream_test.cpp
> [15_1] fix memory leakage of tm_ostream

- System/Memory/fast_alloc.cpp
- tests/System/Memory/fast_alloc_test.cpp
如果分配新的小对象池，原来小对象池的尾部空间会被浪费，造成内存泄漏。
> [15_1] test of memory leakage  in certain case

- Data/Scheme/block.cpp
|        ns/character |         character/s |    err% |     total | benchmark
|              106.74 |        9,368,266.86 |    2.9% |      0.17 | `parsing large group of simple element`(this testcase invokes `block_to_scheme_tree`)
|              120.09 |        8,327,354.01 |    1.2% |      0.17 | `parsing group of complex tree`(this testcase invokes `block_to_scheme_tree`)
|              178.78 |        5,593,349.15 |    1.0% |      0.26 | `parsing single tree with complex structure`(this testcase invokes `string_to_scheme_tree`, and is not added to last pr)
|        ns/character |         character/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:-------- …
> [8_5] Optimize string_to_scheme_tree

- Kernel/Containers/array.ipp
- Kernel/Types/string.cpp
- System/Memory/fast_alloc.hpp
- System/Memory/impl/fast_alloc.cpp
- System/Memory/impl/je_malloc.cpp
- System/Memory/impl/mi_malloc.cpp
use `realloc` to optimize performance
> [8_6] draft of tm_resize_array and fast_realloc

- Kernel/Types/string.cpp
- bench/Kernel/Types/string_bench.cpp
Optimize comparison of two string by dictionary order. After this work, performance of large string comparison is improved twice, however short one is not improved.
|               22.16 |       45,121,128.76 |    0.2% |      0.01 | `compare string`
|              145.29 |        6,882,788.16 |    1.5% |      0.01 | `compare larger string`
|               23.05 |       43,390,782.34 |    4.6% |      0.01 | `compare string`
|               68.25 |       14,651,940.51 |    1.5% | …
> [8_8] Optimize comparison between string

- Kernel/Types/string.cpp
- bench/Kernel/Types/string_bench.cpp
Optimize comparison of two string by dictionary order. After this work, performance of large string comparison is improved twice, however short one is not improved.
|                7.56 |      132,277,551.74 |    2.1% |      0.01 | `equality of string`
|               71.04 |       14,076,915.97 |    3.9% |      0.01 | `equality of larger string`
|                7.57 |      132,048,943.08 |    0.9% |      0.01 | `equality of string`
|               43.94 |       22,759,046.05 | …
> [8_8] optimization and corresponding benchmarks for string equality comparison

- System/Classes/url.cpp
- bench/System/Classes/url_bench.cpp
```
|            8,400.00 |          119,047.62 |    0.2% |      0.01 | `url descends equal`
|           12,203.41 |           81,944.32 |    0.8% |      0.01 | `url descends concat 2`
|           37,293.00 |           26,814.68 |    0.7% |      0.01 | `url descends concat 8`
|            8,395.67 |          119,109.03 |    0.2% |      0.01 | `url descends equal`
|           12,189.40 |           82,038.51 |    0.5% |      0.01 | `url descends concat 2`
|           32,826.84 | …
```
> [8_9] Perf tuning on descends

- Kernel/Types/analyze.cpp
- Kernel/Types/analyze.hpp
- System/Classes/url.cpp
- bench/System/Classes/url_bench.cpp
```
|            8,395.67 |          119,109.03 |    0.2% |      0.01 | `url descends equal`
|           12,189.40 |           82,038.51 |    0.5% |      0.01 | `url descends concat 2`
|           32,826.84 |           30,462.87 |    0.2% |      0.01 | `url descends concat 8`
|           11,964.64 |           83,579.62 |    0.5% |      0.01 | `url construct 8`
#2  …
```
> [8_9] Perf tuning on url_get_name

- lolly/data/lolly_string.hpp
- lolly/data/lolly_string.ipp
- tests/lolly/data/lolly_string_test.cpp
* introduce `reserve` method;
* works like [`std::basic_string::reserve`](https://zh.cppreference.com/w/cpp/string/basic_string/reserve)
* holds size of array in `a_N` field;
* works like [`std::basic_string::capacity`](https://zh.cppreference.com/w/cpp/string/basic_string/capacity)
* introduce `expand_or_shrink_by` method to accelerate append of string.
* `expand_or_shrink_by` avoid re-allocation whenever possible, so if a large string is shrink by `expand_or_shrink_by`, memory is not released.
* `resize` works like [`std::basic_string::resize`](https://zh.cppreference.com/w/cpp/string/basic_string/resize), sometimes `resize` can be used as [`std::basic_string::shrink_to_fit`](https://zh.cppreference.com/w/cpp/string/basic_string/shrink_to_fit).
* add corresponding tests
use `reserve()` …
> [19_5] improve performance of resize and provide reserve

- System/Classes/url.cpp
- System/Classes/url.hpp
- System/Files/file.cpp
- tests/System/Classes/url_test.cpp
Disable `url ()`.
Unify the method to use `url_none ()`.
> [12_30] url: disable the default url contructor

- Kernel/Containers/list.ipp
- bench/Kernel/Containers/list_bench.cpp
Before:
```
|                0.76 |    1,312,761,217.20 |    3.1% |      0.01 | `last_item 1`
|                3.07 |      325,298,326.95 |    4.5% |      0.01 | `last_item 4`
|               19.44 |       51,427,537.40 |    8.4% |      0.01 | :wavy_dash: `last_item 16` (Unstable with ~59,211.2 iters. Increase `minEpochIterations` to e.g. 592112)
|               57.67 |       17,340,734.42 |    0.7% |      0.01 | `N 32`
|                2.33 |      430,092,564.26 |    1.4% |      0.01 | `contains 1`
|               36.14 |       27,669,848.68 |    4.6% |      0.04 | `contains 16`
|               75.11 |       13,314,333.57 |    3.9% | …
```
> [8_10] list: perf tuning on list_contains slightly

- lolly/data/lolly_tree.hpp
fix name lookup of `as_int` in https://github.com/XmacsLabs/moebius/pull/24
> [21_2] fix name lookup in lolly_tree

- Kernel/Abstractions/basic.hpp
- tests/Kernel/Containers/rel_hashmap_test.cpp
- tests/System/Files/file_test.cpp
- tests/lolly_doctests.hpp
- xmake.lua
- improve document for exception handling
- clear error message to avoid errneous memory growth report
> [15_1] avoid false-positive of memory leakage in test

- Kernel/Types/string.hpp
Use string_u8 to show that the string is encoded in UTF-8. It is identical to string in implementation.
> [21_6] string_u8 as an alias of string

- Kernel/Abstractions/resource.hpp
split from #320 
Build mogan with this pr and necessary modifications. CI is unreliable here.
> [22_1] improve code of resources to use them inside namespace

- .github/workflows/ci-doxygen.yml
- .github/workflows/ci-xmake-linux.yml
- .github/workflows/ci-xmake-macos.yml
- .github/workflows/ci-xmake-mingw.yml
- .github/workflows/ci-xmake-wasm.yml
- .github/workflows/ci-xmake-windows.yml
- lolly/system/shared_lib.cpp
- lolly/system/shared_lib.hpp
- tests/lolly/system/example_dynamic_library.cpp
- tests/lolly/system/shared_lib_test.cpp
- xmake.lua
TODO: add proper configuration on wasm
> [22_2] add api to load shared library

- bench/lolly/data/numeral_bench.cpp
- lolly/data/numeral.cpp
- tests/lolly/data/numeral_test.cpp
`to_hex` faster 50%, `as_hexadecimal` faster 82%!!!
| complexityN |               ns/op |                op/s |    err% |     total | benchmark 
|------------:|--------------------:|--------------------:|--------:|----------:|:----------
|           1 |                3.03 |      329,610,514.51 |    2.3% |      0.02 | `convert hexadecimal string to int`
|           1 |               12.77 |       78,320,857.02 |    1.9% |      0.06 | `convert signed int to hexadecimal string`
|           1 |               13.15 |       76,026,752.24 |    1.1% |      0.06 | `convert unsigned int to hexadecimal string`
|           2 |                3.91 |      255,599,303.35 |    4.7% |      0.02 | `convert hexadecimal string to int`
|           2 |               12.69 |       78,811,782.13 |    1.0% | …
> [8_11] boost performance of api converting number to hexadecimal string

- Kernel/Types/string.cpp
- Kernel/Types/string.hpp
- bench/Kernel/Types/string_bench.cpp
- tests/Kernel/Types/string_test.cpp
see also #305 
`operator<<` faster 2-3x than before
|               35.13 |       28,463,649.27 |    3.9% |      0.22 | `construct string`
|                2.66 |      376,488,992.00 |    1.7% |      0.24 | `equality of string`
|               17.68 |       56,561,986.49 |    1.0% |      0.23 | `equality of larger string`
|                4.14 |      241,610,858.14 |    0.9% |      0.24 | `compare string`
|                8.09 |      123,542,843.98 |    2.1% |      0.24 | `compare larger string`
|               18.23 |       54,847,647.47 |    0.6% |      0.24 | `slice string`
|               24.93 |       40,119,524.68 |    2.0% | …
> [8_12] improve strategy of expanding string for performance 

- lolly/data/numeral.cpp
- lolly/data/numeral.hpp
- tests/lolly/data/numeral_test.cpp
> [19_3] port one-param as_hexadecimal to lolly

- Kernel/Types/string.cpp
- bench/Kernel/Types/string_bench.cpp
`hash(string)` is 110%-120% faster than before.
|                6.86 |      145,850,216.76 |    0.7% |      0.24 | `hash of string`
|               59.22 |       16,887,153.73 |    1.1% |      0.24 | `hash of larger string`
|                6.22 |      160,754,437.19 |    0.3% |      0.24 | `hash of string`
|               50.64 |       19,747,047.60 |    0.2% |      0.24 | `hash of larger string`
> [8_13] improve performance when calculating hash of string

- bench/lolly/data/numeral_bench.cpp
- lolly/data/numeral.cpp
| complexityN |               ns/op |                op/s |    err% |     total | benchmark
|------------:|--------------------:|--------------------:|--------:|----------:|:----------
|           1 |               16.13 |       61,983,083.42 |    1.1% |      0.08 | `convert unsigned int to hexadecimal string`
|           2 |               17.66 |       56,613,212.10 |    1.6% |      0.09 | `convert unsigned int to hexadecimal string`
|           3 |               18.61 |       53,742,458.03 |    0.4% |      0.09 | `convert unsigned int to hexadecimal string`
|           4 |               20.91 |       47,819,863.10 |    0.6% |      0.10 | `convert unsigned int to hexadecimal string`
|           5 |               24.17 |       41,368,070.45 |    0.4% |      0.12 | `convert unsigned int to …
> [8_11] optimize performance of as_hexadecimal

- bench/lolly/data/numeral_bench.cpp
- lolly/data/numeral.cpp
- lolly/data/numeral.hpp
- tests/lolly/data/numeral_test.cpp
9x faster than legacy algorithm
| relative |               ns/op |                op/s |    err% |     total | benchmark
|---------:|--------------------:|--------------------:|--------:|----------:|:----------
|   100.0% |          741,626.67 |            1,348.39 |    0.6% |      0.11 | `convert document to hexadecimal string, legacy`
| 1,107.8% |           66,947.70 |           14,937.03 |    1.0% |      0.11 | `convert document to hexadecimal string, using binary_to_hexadecimal`
> [8_11] add binary_to_hexadecimal interface

- lolly/data/numeral.cpp
- lolly/data/numeral.hpp
- tests/lolly/data/numeral_test.cpp
`as_hexadecimal` used to receive int as the input, we should not change the semantics in lolly.
That's why I rename the interface.
> [19_3] Rename as_hexadecimal to uint32_to_Hex

- Kernel/Types/string.cpp
- Kernel/Types/string.hpp
- bench/Kernel/Types/string_bench.cpp
- tests/Kernel/Types/string_test.cpp
This pr ensure the layout consistency between array and string, by make member pointer appears at the same position of class, so that union inside tree will not be broken.
#331 
```cpp
class string{
int n;
int a_N;
char* a;
//...
}
template<class T>
class array<T>{
int n;
T* a;
//...
}
```
this pr
```cpp
class string{
int n;
char* a;
int a_N;
//...
}
template<class T>
class array<T>{
int n;
T* a;
//...
}
```
|               28.76 |       34,766,499.89 |    1.9% |      0.23 | `construct string`
|                2.15 |      465,519,808.15 |    1.1% |      0.24 | `equality of string`
|               12.29 |       81,372,418.85 |    3.4% …
> [8_12] improve strategy of expanding string for performance

- bin/list_tests.sh
- docs/guide/Test.md
- docs/zh/guide/Test.md
增加了列出test项目的脚本（因为原有的xmake show -l targets 不能正常工作， 以 _test 结尾的都是被默认隐藏（set_default(false)）的子 target）
并修正了文档运行测试的描述
> support ./bin/list_tests and fix the docs
